#!/usr/bin/env python3
"""
Create a two-panel Sentinel-2 figure:

    Image (A): single-date cloud-masked Sentinel-2 RGB image
    Image (B): Oct-Dec median composite Sentinel-2 RGB image

Image (A) should be generated by:
    scripts/download_single_scene/download_s2_single_date_rgb_2023.py

Expected composite band paths:
    data/raw/sentinel_gemini/BD_COASTAL_BBOX/S2_2023_octdec_B4_mosaic_10m_lzw.tif
    data/raw/sentinel_gemini/BD_COASTAL_BBOX/S2_2023_octdec_B3_mosaic_10m_lzw.tif
    data/raw/sentinel_gemini/BD_COASTAL_BBOX/S2_2023_octdec_B2_mosaic_10m_lzw.tif

Example run using the bbox from the map:
    python scripts/visualization/make_s2_single_vs_composite_map.py \
        --single-rgb data/raw/sentinel_single_scene/s2_2023_10_18_single_date_rgb.tif \
        --bbox 90.20 22.30 90.283333 22.366667 \
        --year 2023 \
        --out outputs/figures/compare_single_vs_composite_s2_2023.png

BBOX order:
    min_lon min_lat max_lon max_lat

Approximate bbox explanation:
    90°12′E = 90.20
    90°17′E = 90.283333
    22°18′N = 22.30
    22°22′N = 22.366667

Reproduction and AOI adaptation
-------------------------------
Workflow role: Turn prepared rasters, vectors, and tables into thesis-ready figures.

Run commands from the repository root after activating the project environment and
installing ``requirements.txt``. Keep immutable raw inputs separate from generated
intermediate and output products, and create a new output directory for each AOI/run.

Interface and data contract
~~~~~~~~~~~~~~~~~~~~~~~~~~~
The command-line interface exposes ``--single-rgb``, ``--comp-dir``, ``--year``, ``--comp-red``, ``--comp-green``, ``--comp-blue``, ``--bbox``, ``--out``, ``--dpi``, ``--nodata``, ``--title-a``, ``--title-b``, ``--north-arrow``, ``--missing-color``, ``--stretch-low``, ``--stretch-high``. Run the ``--help`` command below for required values, defaults, and accepted choices.
Inputs must exist before execution. Outputs are written to the CLI destinations or
to the path constants/defaults documented above and in the parser. Preserve CRS,
transform, resolution, nodata, band/feature order, and class IDs between dependent
stages; those properties are part of the analytical data contract.

Adapting to another area of interest
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Replace raster/vector/palette paths with target-AOI products and verify matching CRS, extent, class IDs, units, and map annotations before publication.
Record the replacement AOI, acquisition dates, CRS, resolution, class mapping, random
seed, and software environment. Validate intermediate dimensions/statistics and inspect
final maps or tables before using them in analysis or publication.
"""

from __future__ import annotations

import argparse
import io
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import matplotlib.pyplot as plt
import numpy as np
import rasterio
from matplotlib.offsetbox import AnnotationBbox, OffsetImage
from matplotlib.patches import Rectangle
from matplotlib.ticker import FuncFormatter
from PIL import Image
from rasterio.warp import transform_bounds
from rasterio.windows import from_bounds

try:
    import cairosvg

    HAVE_SVG = True
except Exception:
    HAVE_SVG = False


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_COMP_DIR = Path("data/raw/sentinel_gemini/BD_COASTAL_BBOX")
DEFAULT_NORTH_ARROW = Path("assets/maps/NorthArrow.svg")

NODATA_DEFAULT = 65535


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def jst_now() -> str:
    return datetime.now(ZoneInfo("Asia/Tokyo")).strftime("%Y-%m-%d %H:%M:%S UTC+09:00")


def log(msg: str) -> None:
    print(f"[{jst_now()}] {msg}", flush=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Make two-panel Sentinel-2 single-date vs Oct-Dec composite RGB map."
    )

    p.add_argument(
        "--single-rgb",
        type=Path,
        required=True,
        help=(
            "Single-date cloud-masked RGB GeoTIFF. "
            "Expected band order: B4, B3, B2. "
            "Masked/cloud pixels should have nodata value 65535."
        ),
    )

    p.add_argument(
        "--comp-dir",
        type=Path,
        default=DEFAULT_COMP_DIR,
        help="Directory containing Sentinel-2 Oct-Dec composite bands.",
    )

    p.add_argument(
        "--year",
        type=int,
        default=2023,
        help="Composite year. Default: 2023.",
    )

    p.add_argument(
        "--comp-red",
        type=Path,
        default=None,
        help="Optional path to composite B4 GeoTIFF. If omitted, built from --comp-dir and --year.",
    )
    p.add_argument(
        "--comp-green",
        type=Path,
        default=None,
        help="Optional path to composite B3 GeoTIFF. If omitted, built from --comp-dir and --year.",
    )
    p.add_argument(
        "--comp-blue",
        type=Path,
        default=None,
        help="Optional path to composite B2 GeoTIFF. If omitted, built from --comp-dir and --year.",
    )

    p.add_argument(
        "--bbox",
        type=float,
        nargs=4,
        required=True,
        metavar=("MIN_LON", "MIN_LAT", "MAX_LON", "MAX_LAT"),
        help="Map bounding box in EPSG:4326.",
    )

    p.add_argument(
        "--out",
        type=Path,
        default=Path("outputs/figures/compare_single_vs_composite_s2_2023.png"),
        help="Output figure path.",
    )

    p.add_argument("--dpi", type=int, default=300)
    p.add_argument("--nodata", type=float, default=NODATA_DEFAULT)

    p.add_argument("--title-a", type=str, default="Image (A)")
    p.add_argument("--title-b", type=str, default="Image (B)")

    p.add_argument(
        "--north-arrow",
        type=Path,
        default=DEFAULT_NORTH_ARROW,
        help="North arrow SVG path.",
    )

    p.add_argument(
        "--missing-color",
        type=str,
        default="white",
        help="Color used for nodata/cloud-masked pixels. Default: white.",
    )

    p.add_argument(
        "--stretch-low",
        type=float,
        default=2.0,
        help="Lower percentile for RGB stretch.",
    )

    p.add_argument(
        "--stretch-high",
        type=float,
        default=98.0,
        help="Upper percentile for RGB stretch.",
    )

    return p.parse_args()


def resolve_composite_paths(args: argparse.Namespace) -> tuple[Path, Path, Path]:
    comp_dir = resolve_path(args.comp_dir)

    red = (
        resolve_path(args.comp_red)
        if args.comp_red
        else comp_dir / f"S2_{args.year}_octdec_B4_mosaic_10m_lzw.tif"
    )
    green = (
        resolve_path(args.comp_green)
        if args.comp_green
        else comp_dir / f"S2_{args.year}_octdec_B3_mosaic_10m_lzw.tif"
    )
    blue = (
        resolve_path(args.comp_blue)
        if args.comp_blue
        else comp_dir / f"S2_{args.year}_octdec_B2_mosaic_10m_lzw.tif"
    )

    for path in [red, green, blue]:
        if not path.exists():
            raise FileNotFoundError(f"Composite band not found: {path}")

    return red, green, blue


def decimal_degree_to_dm(value: float, axis: str) -> str:
    if axis == "lon":
        direction = "E" if value >= 0 else "W"
    else:
        direction = "N" if value >= 0 else "S"

    value_abs = abs(value)
    deg = int(value_abs)
    minutes = int(round((value_abs - deg) * 60))

    if minutes == 60:
        deg += 1
        minutes = 0

    return f"{deg}°{minutes:02d}′{direction}"


def assert_bbox_overlaps_raster(path: Path, bbox4326: list[float], label: str) -> None:
    with rasterio.open(path) as src:
        bounds_src = transform_bounds("EPSG:4326", src.crs, *bbox4326, densify_pts=21)
        req_left, req_bottom, req_right, req_top = bounds_src
        src_left, src_bottom, src_right, src_top = src.bounds

    overlaps = (
        req_left < src_right
        and req_right > src_left
        and req_bottom < src_top
        and req_top > src_bottom
    )

    if not overlaps:
        raise ValueError(
            f"Requested --bbox does not overlap {label}. "
            f"bbox(EPSG:4326)={bbox4326}; raster={path}; "
            f"raster bounds=left={src_left:.6f}, bottom={src_bottom:.6f}, "
            f"right={src_right:.6f}, top={src_top:.6f}."
        )


def window_extent(src: rasterio.DatasetReader, window) -> tuple[float, float, float, float]:
    transform = src.window_transform(window)

    left = transform.c
    top = transform.f
    right = left + transform.a * window.width
    bottom = top + transform.e * window.height

    return left, right, bottom, top


def read_crop_multiband_rgb(
    path: Path,
    bbox4326: list[float],
    nodata: float,
    label: str,
) -> tuple[np.ndarray, tuple[float, float, float, float], str]:
    """
    Read a 3-band RGB GeoTIFF.

    Expected band order:
        band 1 = Red/B4
        band 2 = Green/B3
        band 3 = Blue/B2
    """
    path = resolve_path(path)

    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")

    assert_bbox_overlaps_raster(path, bbox4326, label)

    with rasterio.open(path) as src:
        if src.count < 3:
            raise ValueError(
                f"{path} has {src.count} band(s), but at least 3 RGB bands are required."
            )

        bounds_src = transform_bounds("EPSG:4326", src.crs, *bbox4326, densify_pts=21)
        window = from_bounds(*bounds_src, transform=src.transform)

        arr = src.read(
            [1, 2, 3],
            window=window,
            boundless=True,
            fill_value=nodata,
        ).astype("float32")

        extent = window_extent(src, window)
        crs_text = src.crs.to_string()

    arr[arr == nodata] = np.nan
    arr[arr <= 0] = np.nan

    return arr, extent, crs_text


def read_crop_single_band(
    path: Path,
    bbox4326: list[float],
    nodata: float,
    label: str,
) -> tuple[np.ndarray, tuple[float, float, float, float], str]:
    path = resolve_path(path)

    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")

    assert_bbox_overlaps_raster(path, bbox4326, label)

    with rasterio.open(path) as src:
        bounds_src = transform_bounds("EPSG:4326", src.crs, *bbox4326, densify_pts=21)
        window = from_bounds(*bounds_src, transform=src.transform)

        arr = src.read(
            1,
            window=window,
            boundless=True,
            fill_value=nodata,
        ).astype("float32")

        extent = window_extent(src, window)
        crs_text = src.crs.to_string()

    arr[arr == nodata] = np.nan
    arr[arr <= 0] = np.nan

    return arr, extent, crs_text


def read_crop_composite_rgb(
    red_path: Path,
    green_path: Path,
    blue_path: Path,
    bbox4326: list[float],
    nodata: float,
) -> tuple[np.ndarray, tuple[float, float, float, float], str]:
    r, extent, crs_text = read_crop_single_band(
        red_path,
        bbox4326,
        nodata,
        label="Composite red band B4",
    )
    g, _, _ = read_crop_single_band(
        green_path,
        bbox4326,
        nodata,
        label="Composite green band B3",
    )
    b, _, _ = read_crop_single_band(
        blue_path,
        bbox4326,
        nodata,
        label="Composite blue band B2",
    )

    min_h = min(r.shape[0], g.shape[0], b.shape[0])
    min_w = min(r.shape[1], g.shape[1], b.shape[1])

    rgb = np.stack(
        [
            r[:min_h, :min_w],
            g[:min_h, :min_w],
            b[:min_h, :min_w],
        ],
        axis=0,
    )

    return rgb, extent, crs_text


def parse_color_to_rgb01(color: str) -> tuple[float, float, float]:
    """
    Supports a few simple color names and hex colors.
    """
    color = color.strip().lower()

    simple = {
        "white": (1.0, 1.0, 1.0),
        "black": (0.0, 0.0, 0.0),
        "gray": (0.75, 0.75, 0.75),
        "grey": (0.75, 0.75, 0.75),
        "red": (1.0, 0.0, 0.0),
    }

    if color in simple:
        return simple[color]

    if color.startswith("#") and len(color) == 7:
        r = int(color[1:3], 16) / 255.0
        g = int(color[3:5], 16) / 255.0
        b = int(color[5:7], 16) / 255.0
        return r, g, b

    raise ValueError(
        f"Unsupported --missing-color: {color}. "
        "Use white, black, gray, red, or hex format such as #FFFFFF."
    )


def stretch_rgb(
    rgb: np.ndarray,
    p_low: float,
    p_high: float,
    missing_color: tuple[float, float, float],
) -> np.ndarray:
    """
    Percentile stretch RGB array.

    Input shape:
        3, H, W

    Output shape:
        H, W, 3
    """
    out = np.zeros_like(rgb, dtype="float32")

    for i in range(3):
        band = rgb[i]
        valid = np.isfinite(band)

        if valid.sum() == 0:
            continue

        lo, hi = np.nanpercentile(band, [p_low, p_high])

        if hi <= lo:
            hi = lo + 1

        out[i] = (band - lo) / (hi - lo)

    out = np.clip(out, 0, 1)

    # Missing/cloud-masked pixels are displayed using the selected missing color.
    missing = ~np.isfinite(rgb).all(axis=0)
    out[0, missing] = missing_color[0]
    out[1, missing] = missing_color[1]
    out[2, missing] = missing_color[2]

    return np.moveaxis(out, 0, -1)


def rgb_valid_missing_stats(rgb: np.ndarray, label: str) -> None:
    valid = np.isfinite(rgb).all(axis=0)
    total = valid.size
    valid_count = int(valid.sum())
    missing_count = total - valid_count

    valid_pct = valid_count / total * 100 if total else 0
    missing_pct = missing_count / total * 100 if total else 0

    log(
        f"{label}: valid pixels = {valid_pct:.2f}%, "
        f"missing/cloud-masked pixels = {missing_pct:.2f}%"
    )


def require_valid_rgb(rgb: np.ndarray, label: str, bbox: list[float]) -> None:
    valid = np.isfinite(rgb).all(axis=0)

    if not np.any(valid):
        raise ValueError(
            f"{label} has no valid pixels inside --bbox {bbox}. "
            "Choose another bbox or check the input raster."
        )


def setup_axis(
    ax,
    bbox: list[float],
    show_left_labels: bool = True,
    show_right_labels: bool = True,
    show_bottom_labels: bool = True,
    show_top_labels: bool = True,
) -> None:
    min_lon, min_lat, max_lon, max_lat = bbox

    ax.set_xlim(min_lon, max_lon)
    ax.set_ylim(min_lat, max_lat)

    xticks = [
        min_lon,
        min_lon + (max_lon - min_lon) * 0.5,
        max_lon,
    ]
    yticks = [
        min_lat,
        min_lat + (max_lat - min_lat) * 0.5,
        max_lat,
    ]

    ax.set_xticks(xticks)
    ax.set_yticks(yticks)

    ax.xaxis.set_major_formatter(
        FuncFormatter(lambda x, pos: decimal_degree_to_dm(x, axis="lon"))
    )
    ax.yaxis.set_major_formatter(
        FuncFormatter(lambda y, pos: decimal_degree_to_dm(y, axis="lat"))
    )

    ax.tick_params(
        axis="both",
        labelsize=8,
        direction="inout",
        length=3,
        top=True,
        right=True,
        bottom=True,
        left=True,
        labeltop=show_top_labels,
        labelbottom=show_bottom_labels,
        labelleft=show_left_labels,
        labelright=show_right_labels,
        pad=3,
    )

    ax.grid(color="black", linewidth=0.45, alpha=0.55)

    for spine in ax.spines.values():
        spine.set_edgecolor("blue")
        spine.set_linewidth(1.2)

    ax.set_aspect("equal", adjustable="box")


def add_panel_label(ax, label: str) -> None:
    ax.text(
        0.03,
        0.95,
        label,
        transform=ax.transAxes,
        fontsize=11,
        fontweight="bold",
        va="top",
        ha="left",
        bbox=dict(
            facecolor="white",
            edgecolor="lightgray",
            boxstyle="square,pad=0.25",
        ),
        zorder=10,
    )


def add_scalebar(ax, bbox: list[float], length_km: float = 2.0) -> None:
    """
    Add approximate lon/lat scale bar for small map areas.
    """
    min_lon, min_lat, max_lon, max_lat = bbox

    center_lat = (min_lat + max_lat) / 2
    km_per_degree_lon = 111.32 * np.cos(np.deg2rad(center_lat))
    length_deg = length_km / km_per_degree_lon

    x0 = max_lon - length_deg - (max_lon - min_lon) * 0.08
    y0 = min_lat + (max_lat - min_lat) * 0.075

    bar_h = (max_lat - min_lat) * 0.018

    ax.add_patch(
        Rectangle(
            (x0, y0),
            length_deg / 2,
            bar_h,
            facecolor="black",
            edgecolor="black",
            linewidth=0.8,
            zorder=8,
        )
    )
    ax.add_patch(
        Rectangle(
            (x0 + length_deg / 2, y0),
            length_deg / 2,
            bar_h,
            facecolor="white",
            edgecolor="black",
            linewidth=0.8,
            zorder=8,
        )
    )

    ax.text(
        x0,
        y0 + bar_h * 2.0,
        "0",
        ha="center",
        va="bottom",
        fontsize=8,
        fontweight="bold",
        color="black",
        zorder=9,
    )

    ax.text(
        x0 + length_deg,
        y0 + bar_h * 2.0,
        f"{int(length_km)} km",
        ha="center",
        va="bottom",
        fontsize=8,
        fontweight="bold",
        color="black",
        zorder=9,
    )


def load_svg_as_image(svg_path: Path, target_height_px: int = 220):
    if not svg_path.exists() or not HAVE_SVG:
        return None

    png_bytes = cairosvg.svg2png(url=str(svg_path), output_height=target_height_px)
    return Image.open(io.BytesIO(png_bytes))


def add_north_arrow(ax, svg_path: Path, xy=(0.90, 0.88), zoom=0.20) -> None:
    img = load_svg_as_image(svg_path, target_height_px=220)

    if img is None:
        ax.annotate(
            "N",
            xy=xy,
            xycoords="axes fraction",
            ha="center",
            va="center",
            fontsize=13,
            fontweight="bold",
            zorder=20,
        )
        ax.annotate(
            "",
            xy=(xy[0], xy[1] - 0.03),
            xytext=(xy[0], xy[1] - 0.13),
            xycoords="axes fraction",
            arrowprops=dict(arrowstyle="-|>", lw=1.3, color="black"),
            zorder=20,
        )
        return

    imagebox = OffsetImage(np.asarray(img), zoom=zoom)
    ab = AnnotationBbox(
        imagebox,
        xy,
        xycoords="axes fraction",
        frameon=False,
        box_alignment=(0.5, 0.5),
        zorder=20,
    )
    ax.add_artist(ab)


def main() -> None:
    args = parse_args()

    args.single_rgb = resolve_path(args.single_rgb)
    args.out = resolve_path(args.out)

    north_arrow = resolve_path(args.north_arrow)
    bbox = list(args.bbox)

    missing_color = parse_color_to_rgb01(args.missing_color)

    comp_red, comp_green, comp_blue = resolve_composite_paths(args)

    log(f"Single-date RGB image: {args.single_rgb}")
    log(f"Composite red band B4: {comp_red}")
    log(f"Composite green band B3: {comp_green}")
    log(f"Composite blue band B2: {comp_blue}")
    log(f"Map bbox EPSG:4326: {bbox}")

    log("Reading single-date RGB image for Image (A)...")
    single_rgb, single_extent, single_crs = read_crop_multiband_rgb(
        args.single_rgb,
        bbox,
        args.nodata,
        label="Single-date RGB image",
    )

    log("Reading Oct-Dec composite RGB bands for Image (B)...")
    comp_rgb, comp_extent, comp_crs = read_crop_composite_rgb(
        comp_red,
        comp_green,
        comp_blue,
        bbox,
        args.nodata,
    )

    if single_crs != "EPSG:4326":
        log(
            f"WARNING: single-date image CRS is {single_crs}. "
            "The script works best when the single-date image is exported as EPSG:4326."
        )

    if comp_crs != "EPSG:4326":
        log(
            f"WARNING: composite CRS is {comp_crs}. "
            "The script works best when the composite images are EPSG:4326."
        )

    require_valid_rgb(single_rgb, "Single-date RGB image", bbox)
    require_valid_rgb(comp_rgb, "Oct-Dec composite RGB image", bbox)

    rgb_valid_missing_stats(single_rgb, "Image (A) single-date")
    rgb_valid_missing_stats(comp_rgb, "Image (B) Oct-Dec composite")

    single_rgb_vis = stretch_rgb(
        single_rgb,
        p_low=args.stretch_low,
        p_high=args.stretch_high,
        missing_color=missing_color,
    )
    comp_rgb_vis = stretch_rgb(
        comp_rgb,
        p_low=args.stretch_low,
        p_high=args.stretch_high,
        missing_color=missing_color,
    )

    fig = plt.figure(figsize=(8.5, 3.7))
    gs = fig.add_gridspec(
        nrows=1,
        ncols=2,
        wspace=0.16,
    )

    ax_a = fig.add_subplot(gs[0])
    ax_b = fig.add_subplot(gs[1])

    ax_a.imshow(single_rgb_vis, extent=single_extent, origin="upper")
    ax_b.imshow(comp_rgb_vis, extent=comp_extent, origin="upper")

    # Avoid duplicated longitude/latitude labels between the two panels.
    setup_axis(
        ax_a,
        bbox,
        show_left_labels=True,
        show_right_labels=False,
        show_bottom_labels=True,
        show_top_labels=True,
    )
    setup_axis(
        ax_b,
        bbox,
        show_left_labels=False,
        show_right_labels=True,
        show_bottom_labels=True,
        show_top_labels=True,
    )

    add_panel_label(ax_a, args.title_a)
    add_panel_label(ax_b, args.title_b)

    add_north_arrow(ax_a, north_arrow, xy=(0.90, 0.88), zoom=0.20)
    add_north_arrow(ax_b, north_arrow, xy=(0.90, 0.88), zoom=0.20)

    add_scalebar(ax_a, bbox, length_km=2)
    add_scalebar(ax_b, bbox, length_km=2)

    args.out.parent.mkdir(parents=True, exist_ok=True)

    plt.savefig(args.out, dpi=args.dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    log(f"Saved figure: {args.out}")
    log("DONE")


if __name__ == "__main__":
    main()
