#!/usr/bin/env python3
"""
Check and summarize AE64 train/val/test NPZ contents.

Expected NPZ keys:
  X_train, y_train, X_val, y_val, X_test, y_test, mu, sigma, feature_names, meta

Example:
python scripts/training/check_ae64_samples_trainvaltest_npz.py \
  --npz data/processed/training/ae64_samples_4upazila_2023_trainvaltest.npz

Optional:
python scripts/training/check_ae64_samples_trainvaltest_npz.py \
  --npz data/processed/training/ae64_samples_4upazila_2023_trainvaltest.npz \
  --show-meta \
  --show-feature-names
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import numpy as np


JST = timezone(timedelta(hours=9))
PROJECT_ROOT = Path(__file__).resolve().parents[2]


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else PROJECT_ROOT / path


def log(message: str) -> None:
    ts = datetime.now(JST).isoformat(timespec="seconds")
    print(f"[{ts}] {message}", flush=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Check AE64 train/val/test NPZ contents.")
    p.add_argument(
        "--npz",
        type=Path,
        required=True,
        help="Path to NPZ file generated by extract_ae64_samples_trainvaltest.py",
    )
    p.add_argument(
        "--show-meta",
        action="store_true",
        help="Print full parsed meta JSON.",
    )
    p.add_argument(
        "--show-feature-names",
        action="store_true",
        help="Print all feature names.",
    )
    p.add_argument(
        "--preview-rows",
        type=int,
        default=3,
        help="Number of rows to preview from each split (default: 3).",
    )
    return p.parse_args()


def format_shape(arr: np.ndarray) -> str:
    return f"shape={arr.shape}, dtype={arr.dtype}"


def count_classes(y: np.ndarray) -> dict[int, int]:
    if y.size == 0:
        return {}
    vals, counts = np.unique(y, return_counts=True)
    return {int(v): int(c) for v, c in zip(vals, counts)}


def summarize_array(name: str, arr: np.ndarray) -> None:
    log(f"{name:<12}: {format_shape(arr)}")
    if arr.size == 0:
        log(f"{name:<12}: empty array")
        return

    if np.issubdtype(arr.dtype, np.number):
        finite_mask = np.isfinite(arr)
        finite_ratio = float(finite_mask.mean()) if finite_mask.size > 0 else 1.0
        log(
            f"{name:<12}: min={np.nanmin(arr):.6f}, "
            f"max={np.nanmax(arr):.6f}, "
            f"mean={np.nanmean(arr):.6f}, "
            f"std={np.nanstd(arr):.6f}, "
            f"finite_ratio={finite_ratio:.6f}"
        )


def preview_rows(name: str, arr: np.ndarray, n: int) -> None:
    if arr.ndim != 2 or arr.shape[0] == 0 or n <= 0:
        return
    rows = min(n, arr.shape[0])
    log(f"{name} first {rows} row(s), first 8 feature(s):")
    for i in range(rows):
        preview = ", ".join(f"{float(x):.6f}" for x in arr[i, :8])
        print(f"  row[{i}]: [{preview}{', ...' if arr.shape[1] > 8 else ''}]")


def main() -> None:
    args = parse_args()
    args.npz = resolve_path(args.npz)

    if not args.npz.exists():
        raise SystemExit(f"NPZ not found: {args.npz}")

    log(f"Checking NPZ: {args.npz}")

    data = np.load(args.npz, allow_pickle=True)
    keys = list(data.keys())
    log(f"keys: {keys}")

    required_keys = [
        "X_train", "y_train",
        "X_val", "y_val",
        "X_test", "y_test",
        "mu", "sigma",
        "feature_names", "meta",
    ]
    missing = [k for k in required_keys if k not in data]
    if missing:
        raise SystemExit(f"Missing required keys: {missing}")

    X_train = data["X_train"]
    y_train = data["y_train"]
    X_val = data["X_val"]
    y_val = data["y_val"]
    X_test = data["X_test"]
    y_test = data["y_test"]
    mu = data["mu"]
    sigma = data["sigma"]
    feature_names = data["feature_names"]
    meta_raw = data["meta"]

    if isinstance(meta_raw, np.ndarray) and meta_raw.shape == ():
        meta_raw = meta_raw.item()

    try:
        meta: dict[str, Any] = json.loads(meta_raw)
    except Exception as e:
        raise SystemExit(f"Could not parse meta JSON: {e}")

    summarize_array("X_train", X_train)
    summarize_array("y_train", y_train)
    summarize_array("X_val", X_val)
    summarize_array("y_val", y_val)
    summarize_array("X_test", X_test)
    summarize_array("y_test", y_test)
    summarize_array("mu", mu)
    summarize_array("sigma", sigma)

    log(f"feature_names: shape={feature_names.shape}, dtype={feature_names.dtype}")

    # Shape consistency checks
    if X_train.ndim != 2 or X_val.ndim != 2 or X_test.ndim != 2:
        raise SystemExit("X arrays must all be 2D.")
    if y_train.ndim != 1 or y_val.ndim != 1 or y_test.ndim != 1:
        raise SystemExit("y arrays must all be 1D.")
    if X_train.shape[0] != y_train.shape[0]:
        raise SystemExit(f"Mismatch: X_train rows={X_train.shape[0]} vs y_train size={y_train.shape[0]}")
    if X_val.shape[0] != y_val.shape[0]:
        raise SystemExit(f"Mismatch: X_val rows={X_val.shape[0]} vs y_val size={y_val.shape[0]}")
    if X_test.shape[0] != y_test.shape[0]:
        raise SystemExit(f"Mismatch: X_test rows={X_test.shape[0]} vs y_test size={y_test.shape[0]}")

    feat_dim = X_train.shape[1]
    if X_val.shape[1] != feat_dim or X_test.shape[1] != feat_dim:
        raise SystemExit(
            f"Feature dimension mismatch: "
            f"train={X_train.shape[1]}, val={X_val.shape[1]}, test={X_test.shape[1]}"
        )
    if mu.shape[0] != feat_dim:
        raise SystemExit(f"mu length mismatch: mu={mu.shape[0]} vs feature_dim={feat_dim}")
    if sigma.shape[0] != feat_dim:
        raise SystemExit(f"sigma length mismatch: sigma={sigma.shape[0]} vs feature_dim={feat_dim}")
    if feature_names.shape[0] != feat_dim:
        raise SystemExit(f"feature_names length mismatch: feature_names={feature_names.shape[0]} vs feature_dim={feat_dim}")

    log(f"Feature dimension verified: {feat_dim}")

    # Label checks
    for split_name, y in [("train", y_train), ("val", y_val), ("test", y_test)]:
        if y.size > 0:
            if not np.all((y >= 1) & (y <= 10)):
                raise SystemExit(f"Labels out of expected range 1..10 in y_{split_name}")

    log(f"Train class counts: {count_classes(y_train)}")
    log(f"Val class counts  : {count_classes(y_val)}")
    log(f"Test class counts : {count_classes(y_test)}")

    # Normalization sanity
    zero_sigma = int(np.sum(sigma == 0))
    one_sigma = int(np.sum(sigma == 1.0))
    nonfinite_mu = int(np.sum(~np.isfinite(mu)))
    nonfinite_sigma = int(np.sum(~np.isfinite(sigma)))

    log(f"Normalization check: zero_sigma={zero_sigma}, one_sigma={one_sigma}")
    log(f"Normalization check: nonfinite_mu={nonfinite_mu}, nonfinite_sigma={nonfinite_sigma}")

    if nonfinite_mu > 0 or nonfinite_sigma > 0:
        raise SystemExit("mu or sigma contains non-finite values.")

    preview_rows("X_train", X_train, args.preview_rows)
    preview_rows("X_val", X_val, args.preview_rows)
    preview_rows("X_test", X_test, args.preview_rows)

    if args.show_feature_names:
        log("Feature names:")
        for i, name in enumerate(feature_names.tolist(), start=1):
            print(f"  {i:02d}: {name}")

    # Meta summary
    log("Meta summary:")
    for k in [
        "created_at_jst",
        "ae_path",
        "feature_dim",
        "ae_feature_dim",
        "upazilas",
        "max_per_class",
        "val_frac",
        "test_frac",
        "train_frac",
        "block_size_m",
        "block_px",
        "seed",
        "label_nodata",
        "ae_nodata",
    ]:
        if k in meta:
            print(f"  {k}: {meta[k]}")

    if "final_counts" in meta:
        log("Meta final_counts:")
        print(json.dumps(meta["final_counts"], indent=2))

    if args.show_meta:
        log("Full meta JSON:")
        print(json.dumps(meta, indent=2))

    log("NPZ check completed successfully.")


if __name__ == "__main__":
    main()
